"use client";

import { useActionState } from "react";

import {
  generateAiInsightAction,
  type AiInsightActionState,
} from "@/app/actions";

const initialState: AiInsightActionState = {
  status: "idle",
};

export function AiInsightsTool({ openAiEnabled }: { openAiEnabled: boolean }) {
  const [state, action, pending] = useActionState(
    generateAiInsightAction,
    initialState,
  );

  return (
    <section className="rounded-md border border-[#2c2824]/[0.13] bg-[#fffaf2] p-5">
      <div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">
        <div>
          <p className="zach-ui text-[10px] font-semibold uppercase tracking-[0.24em] text-[#9a7d5f]">
            OpenAI optional
          </p>
          <h1 className="zach-display mt-2 text-4xl font-medium tracking-tight text-[#111820]">
            AI Insights
          </h1>
          <p className="mt-3 max-w-3xl text-sm leading-6 text-[#71685c]">
            Generate cautious, practical daily and weekly summaries using only
            your stored Zach OS data. The app falls back to local summaries when
            `OPENAI_API_KEY` is not configured or an API request fails.
          </p>
        </div>
        <div
          className={`rounded-md border px-3 py-2 text-sm ${
            openAiEnabled
              ? "border-[#7a8c5a]/30 bg-[#7a8c5a]/10 text-[#54683b]"
              : "border-[#b08c3c]/30 bg-[#b08c3c]/10 text-[#725822]"
          }`}
        >
          {openAiEnabled ? "OpenAI enabled" : "OpenAI not configured"}
        </div>
      </div>

      <div className="mt-5 flex flex-col gap-3 sm:flex-row">
        <form action={action}>
          <input name="kind" type="hidden" value="daily" />
          <button
            className="h-10 rounded-md bg-[#bb5d3a] px-4 text-sm font-semibold text-[#f9f4ec] transition hover:bg-[#a94f31] disabled:cursor-not-allowed disabled:opacity-60"
            disabled={pending}
            type="submit"
          >
            {pending ? "Generating..." : "Generate daily summary"}
          </button>
        </form>
        <form action={action}>
          <input name="kind" type="hidden" value="weekly" />
          <button
            className="h-10 rounded-md border border-[#d2c8b8] bg-[#f9f4ec] px-4 text-sm font-semibold text-[#2c2824] transition hover:border-[#b9aa95] disabled:cursor-not-allowed disabled:opacity-60"
            disabled={pending}
            type="submit"
          >
            {pending ? "Generating..." : "Generate weekly report"}
          </button>
        </form>
      </div>

      {state.status !== "idle" && (
        <article className="mt-5 rounded-md border border-[#2c2824]/[0.13] bg-[#f9f4ec] p-4">
          <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
            <h2 className="zach-display text-2xl font-medium text-[#111820]">
              {state.kind === "weekly" ? "Weekly report" : "Daily summary"}
            </h2>
            <p className="text-xs text-[#8c8273]">
              {state.source === "openai" ? "Generated by OpenAI" : "Local fallback"}
              {state.generatedAt ? ` - ${new Date(state.generatedAt).toLocaleString("en-GB")}` : ""}
            </p>
          </div>
          {state.error && (
            <p className="mt-3 rounded-md border border-[#b08c3c]/30 bg-[#b08c3c]/10 px-3 py-2 text-sm text-[#725822]">
              {state.error}
            </p>
          )}
          <div className="mt-4 whitespace-pre-wrap text-sm leading-7 text-[#3a342c]">
            {state.content || "No insight generated."}
          </div>
        </article>
      )}
    </section>
  );
}
