"use client";

import { useActionState } from "react";

import {
  generateAiInsightAction,
  type AiInsightActionState,
} from "@/app/actions";

const initialState: AiInsightActionState = {
  status: "idle",
};

export function AiInsightsTool({ openAiEnabled }: { openAiEnabled: boolean }) {
  const [state, action, pending] = useActionState(
    generateAiInsightAction,
    initialState,
  );

  return (
    <section className="rounded border border-cyan-200/20 bg-gradient-to-br from-cyan-200/[0.08] to-white/[0.025] p-5">
      <div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">
        <div>
          <p className="font-mono text-[0.68rem] uppercase tracking-[0.22em] text-cyan-200/70">
            OpenAI optional
          </p>
          <h1 className="mt-2 text-3xl font-semibold tracking-tight text-white">
            AI Insights
          </h1>
          <p className="mt-3 max-w-3xl text-sm leading-6 text-zinc-400">
            Generate cautious, practical daily and weekly summaries using only
            your stored Zach OS data. The app falls back to local summaries when
            `OPENAI_API_KEY` is not configured or an API request fails.
          </p>
        </div>
        <div
          className={`rounded border px-3 py-2 text-sm ${
            openAiEnabled
              ? "border-emerald-200/25 bg-emerald-300/10 text-emerald-100"
              : "border-amber-200/25 bg-amber-300/10 text-amber-100"
          }`}
        >
          {openAiEnabled ? "OpenAI enabled" : "OpenAI not configured"}
        </div>
      </div>

      <div className="mt-5 flex flex-col gap-3 sm:flex-row">
        <form action={action}>
          <input name="kind" type="hidden" value="daily" />
          <button
            className="h-10 rounded bg-cyan-200 px-4 text-sm font-semibold text-slate-950 transition hover:bg-cyan-100 disabled:cursor-not-allowed disabled:opacity-60"
            disabled={pending}
            type="submit"
          >
            {pending ? "Generating..." : "Generate daily summary"}
          </button>
        </form>
        <form action={action}>
          <input name="kind" type="hidden" value="weekly" />
          <button
            className="h-10 rounded border border-white/10 bg-white/[0.04] px-4 text-sm font-semibold text-zinc-100 transition hover:border-cyan-200/30 hover:bg-cyan-300/10 disabled:cursor-not-allowed disabled:opacity-60"
            disabled={pending}
            type="submit"
          >
            {pending ? "Generating..." : "Generate weekly report"}
          </button>
        </form>
      </div>

      {state.status !== "idle" && (
        <article className="mt-5 rounded border border-white/10 bg-black/20 p-4">
          <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
            <h2 className="text-lg font-semibold text-white">
              {state.kind === "weekly" ? "Weekly report" : "Daily summary"}
            </h2>
            <p className="text-xs text-zinc-500">
              {state.source === "openai" ? "Generated by OpenAI" : "Local fallback"}
              {state.generatedAt ? ` - ${new Date(state.generatedAt).toLocaleString("en-GB")}` : ""}
            </p>
          </div>
          {state.error && (
            <p className="mt-3 rounded border border-amber-200/25 bg-amber-300/10 px-3 py-2 text-sm text-amber-100">
              {state.error}
            </p>
          )}
          <div className="mt-4 whitespace-pre-wrap text-sm leading-7 text-zinc-200">
            {state.content || "No insight generated."}
          </div>
        </article>
      )}
    </section>
  );
}
